name: dev

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
    paths-ignore:
      - 'test/*'
      - '.gitignore'
      - 'docker-compose-separate-containers.yml'
      - 'docker-compose.yml'
      - 'LICENSE'
      - 'Makefile'
      - '*.md'

jobs:
  multiarch-build-debian:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Retrieve version
        run: echo "GIT_DESCRIBE=$(git describe --tags)" >> $GITHUB_ENV

      - name: Get Docker tags for Debian based image
        id: docker_meta_debian
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/nginx-proxy/nginx-proxy
            nginxproxy/nginx-proxy
            jwilder/nginx-proxy
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          labels: |
            org.opencontainers.image.authors=Nicolas Duchon <nicolas.duchon@gmail.com> (@buchdag), Jason Wilder
            org.opencontainers.image.version=${{ env.GIT_DESCRIBE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push the Debian based image
        id: docker_build_debian
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          build-args: NGINX_PROXY_VERSION=1.0.1
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/uacaman/ebov-backend-dev:latest,ghcr.io/uacaman/ebov-backend-dev:${{ steps.date.outputs.date }}
